### ISSUE TITLE
Error while importing pyproj

### ISSUE THREAD

**Issue by yaduart** [jswhit/pyproj#76]
I installed pyproj on a Linux machine.  I do not get any errors while installing pyproj using pip3. 

But, while importing pyproj. I get errors _proj.cpython-34m.so: undefined symbol: __intel_sse2_strcpy.

My linux enviroment:
Linux raijin1 2.6.32-573.22.1.el6.x86_64 #1 SMP Wed Mar 23 03:35:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

My python virtual environment has numpy 1.11.0 and cython 0.24.
(v1) [yxs659@raijin1 tests]$ pip3 list
cycler (0.10.0)
Cython (0.24)
matplotlib (1.5.1)
numpy (1.11.0)
pip (8.1.1)
pyparsing (2.1.1)
pyproj (1.9.5.1)
python-dateutil (2.5.3)
pytz (2016.4)
rHEALPixDGGS (0.5.1)
scipy (0.17.0)
setuptools (20.10.1)
six (1.10.0)
wheel (0.29.0)

The error I get is the following,

(v1) [yxs659@raijin1 tests]$ python3          
Python 3.4.3 (default, Jul 15 2015, 12:53:20) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyproj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/659/yxs659/virt_env/v1/lib/python3.4/site-packages/pyproj/__init__.py", line 51, in <module>
    from pyproj import _proj
ImportError: /home/659/yxs659/virt_env/v1/lib/python3.4/site-packages/pyproj/_proj.cpython-34m.so: undefined symbol: __intel_sse2_strcpy
>>>

**Comment by yaduart** [comment]
Looks like the issue has been solved. The linux machine that I work on uses both icc & gcc compilers. It seems to work when gcc is used to build the package. And the issue seems to have been solved after installing pyproj as given below,

CC=gcc pip3 install pyproj
